### ISSUE TITLE
Same issue as "Cannot run DependenciesGui #183"

### ISSUE THREAD

**Issue by JoeLiu2015** [lucasg/Dependencies#214]
The windows 10 system event log said:

Application: DependenciesGui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32)
   at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32)
   at MS.Internal.FontFace.TypefaceCollection+Enumerator.get_Current()
   at Dependencies.FontFamilyListItem.IsSymbolFont(System.Windows.Media.FontFamily)
   at Dependencies.FontFamilyListItem..ctor(System.Windows.Media.FontFamily)
   at Dependencies.UserSettings.InitializeFontFamilyList()
   at Dependencies.UserSettings.OnInitialized(System.EventArgs)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType, System.Object, Boolean)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at Dependencies.UserSettings..ctor()
   at Dependencies.MainWindow..ctor()
   at Dependencies.App.App_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Dependencies.App.Main()

===========================================================================
I think the internal code should catch the exception.  I try to fixed the code, it works for me:

File:  Dependencies-master\DependenciesGui\UserSettings.xaml.cs
Line: 182
 public UserSettings()
 {
          try {
            InitializeComponent();
          } catch (Exception ex) {
          }
          .....
}
See above code, add "try...catch" for "InitializeComponent();" solve the issue.

**Comment by thorntonryan** [comment]
Thanks @JoeLiu2015 !

I randomly? ran into this same issue. And I agree, I think it was related to #183 .

Applying your suggestion allowed me to compile/run a new version of DependenciesGUI.

And uninstalling `Cascadia Code` and `Cascasdia Mono` allowed the prebuilt versions to start working again.

Thanks for your helpful suggestion!
