### ISSUE TITLE
AppCrash (local user)

### ISSUE THREAD

**Issue by hfiref0x** [lucasg/Dependencies#33]
Hello,

Windows 10 14393, x64

DependenciesGui.exe crash on start. Version 1.8 from latest Release section.

Local user account without administrative privileges - permanent crash on startup.

Running as admin (with elevation) everything work as expected.
Running as admin (without elevation) everything work as expected.

Related Event Log entries

Application Error

> Faulting application name: DependenciesGui.exe, version: 1.7.0.0, time stamp: 0x5b2ac677
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2a65
Exception code: 0xe0434352
Fault offset: 0x000dad12
Faulting process id: 0x17a0
Faulting application start time: 0x01d460a7e4531888

.NET Runtime

> Application: DependenciesGui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at System.ClrPh.PE.InitProperties()
   at System.ClrPh.PE.Load()
   at Dependencies.BinaryCache.GetBinary(System.String)
   at Dependencies.BinaryCache.Load()
   at Dependencies.App.App_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Dependencies.App.Main()

Other executables such as  Dependencies.exe and Pview.exe run well.

p.s.
Forgot to add, exact faulting exe is from Dependencies_x86_Release.
Dependencies_x64_Release - problem not reproducible.

**Comment by lucasg** [comment]
`DependenciesGui.exe` has a "binary cache" : at startup it loads up regularly used dlls like KnownDlls in order to speed up further loadings and to work around the fact that Windows locks loaded dlls. Except this binary cache lookup is quite tricky to implement and has some bugs in the past.

Any DLL loaded is copied into `%LOCALAPPDATA%/Dependencies/BinaryCache/${Arch}` (where `${Arch}` is x64 or x86) and further loads are done from this folder. My guess is your cache is not "clean" anymore, there is probably a corrupted entry that choke Dependencies at startup. You can always clean up the folder and try to restart `DependenciesGui.exe` to solve the issue (the good ol' switching off and on !).

Alternatively, the current master build does not suffer from this issue : https://ci.appveyor.com/api/buildjobs/wj0o9hdahgu9oc6k/artifacts/output%2FDependencies_x86_Release.zip.  (I've fixed some bugs plaguing the x86 version in the meantime, it may also have fixed your crash)

**Comment by hfiref0x** [comment]
Cleaning binary cache solved this crash, thanks.
