### ISSUE TITLE
1.9.0.0 Crash on Winzip32.exe (version 10, 6667) Windows 10 Pro Latest

### ISSUE THREAD

**Issue by storkinsj** [lucasg/Dependencies#72]
Running dependencies.exe as follows:

C:\bin>Dependencies.exe -chain "\Program Files (x86)\WinZip\WINZIP32.EXE"

Results in an unhandled exception:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 294
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.Program.DumpDependencyChain(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 491
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 589

It felt like a considerable delay happened first.

**Comment by lucasg** [comment]
After several hours of processing (which is an issue itself) I managed to get the results without `Dependencies` ever crashing, meaning the issue may come from the difference in our system and not in the application folder.

I'll release a "troubleshooting" version in order to log the resolution made at each step, but in the mean time if you're familiar with DbgView you can trace it yourself :

![image](https://user-images.githubusercontent.com/2520861/59661850-05401900-91ac-11e9-826f-1ccf71ed15b3.png)

**Results** :

[WinZip32.exe.txt](https://github.com/lucasg/Dependencies/files/3300273/WinZip32.exe.txt)

**Comment by techxdave** [comment]
I am seeing the same crash (also version 1.9.0)...

```
C:\bin>Dependencies.exe -chain "C:\Windows\System32\msvcr120.dll"

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 294
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.Program.DumpDependencyChain(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 491
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 589
```
Where can I get the debug version?

**Comment by lucasg** [comment]
you can download the debug build artifacts here : https://ci.appveyor.com/project/lucasg/dependencies/history

**Beware** : it can be excruciatingly long to run the debug analysis on this binary (several hours in my case)

**Comment by lucasg** [comment]
> I am seeing the same crash (also version 1.9.0)...
> 
> ```
> C:\bin>Dependencies.exe -chain "C:\Windows\System32\msvcr120.dll"
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 294
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
>    at Dependencies.Program.DumpDependencyChain(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 491
>    at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 589
> ```
> 
> Where can I get the debug version?

@techxdave : I've replicated the bug with the 1.9 release, but the current dev builds do not trigger it anymore (I must have fixed it in the meantime).

Until I release the v1.10, you can download the build artifacts here : https://ci.appveyor.com/api/buildjobs/vleh504cnvrmsacb/artifacts/output%2FDependencies_x64_Release.zip
