### ISSUE TITLE
Unhandled XML exception Win10 Preview

### ISSUE THREAD

**Issue by andyfmidd** [lucasg/Dependencies#75]
Dragging a .Net application onto the Dependencies gui (V1.9) does not show anything, though it says loaded.
Using File Open on the same .Net app causes Dependencies to terminate.
(Win 10 Insider 18922 (64bit).
Event log: Application: DependenciesGui.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(System.Xml.XmlReader, System.Xml.Linq.LoadOptions)
   at Dependencies.SxsManifest.ParseSxsManifest(System.IO.Stream)
   at Dependencies.SxsManifest.ExtractDependenciesFromSxsManifest(System.IO.Stream, System.String, System.String, Boolean)
   at Dependencies.SxsManifest.ExtractDependenciesFromSxsManifestFile(System.String, System.String, System.String, Boolean)
   at Dependencies.SxsManifest.ExtractDependenciesFromSxsElement(System.Xml.Linq.XElement, System.String, System.String, Boolean)
   at Dependencies.SxsManifest.ExtractDependenciesFromSxsManifest(System.IO.Stream, System.String, System.String, Boolean)
   at Dependencies.SxsManifest.ExtractDependenciesFromSxsManifestFile(System.String, System.String, System.String, Boolean)
   at Dependencies.SxsManifest.GetSxsEntries(Dependencies.ClrPh.PE)
   at Dependencies.DependencyWindow.InitializeView()
   at Dependencies.MainWindow.OpenNewDependencyWindow(System.String)
   at System.Windows.Input.CommandBinding.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(System.Object, System.Windows.Input.ExecutedRoutedEventArgs, System.Windows.Input.CommandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Windows.Input.CommandBindingCollection, System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.FindCommandBinding(System.Object, System.Windows.RoutedEventArgs, System.Windows.Input.ICommand, Boolean)
   at System.Windows.Input.CommandManager.OnExecuted(System.Object, System.Windows.Input.ExecutedRoutedEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(System.Object, System.Windows.IInputElement, Boolean)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Dependencies.App.Main()

Fault bucket 1372492181216343969, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: DependenciesGui.exe
P2: 1.9.0.0
P3: 5c043c76
P4: System.Xml
P5: 4.8.3752.0
P6: 5c7a2412
P7: b85
P8: 27
P9: System.Xml.XmlException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD93.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD43B.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD47B.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20190610 1 Event Collector_0_inject.etl
\\?\C:\Users\andy\AppData\Local\Temp\WERD4DA.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\Users\andy\AppData\Local\Temp\WERD4DB.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD4D7.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD516.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_DependenciesGui._67bed98c7df6df2d40f5a0c1624e98a48a97fc54_469e8972_55255522-228d-48b5-865e-fd2f103c055d

Analysis symbol: 
Rechecking for solution: 0
Report Id: f1aea2eb-8cb7-4c80-8a70-4c746e2a8698
Report Status: 268435456
Hashed bucket: 04ba0a13e1341be9a30c125df666b7a1
Cab Guid: 0

and
Faulting application name: DependenciesGui.exe, version: 1.9.0.0, time stamp: 0x5c043c76
Faulting module name: KERNELBASE.dll, version: 10.0.18922.1000, time stamp: 0xb083026d
Exception code: 0xe0434352
Fault offset: 0x000000000002ed69
Faulting process ID: 0x7bc
Faulting application start time: 0x01d530c9b23a032c
Faulting application path: D:\Software\Dependencies_x64_Release\DependenciesGui.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 47311ac0-b4ed-4c2f-abe7-5f1aa232f4fb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by lucasg** [comment]
Interesting, do you know which binary triggers the bug (path & hash) ?
