### ISSUE TITLE
System.ArgumentException in Dependencies.ShellIcon.GetIcon

### ISSUE THREAD

**Issue by rweijnen** [lucasg/Dependencies#8]
System.ArgumentException occurred
  HResult=0x80070057
  Message=Win32 handle that was passed to Icon is not valid or is the wrong type.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at Dependencies.ShellIcon.GetIcon(String fileName, UInt32 flags) in C:\Users\RemkoW\source\repos\Dependencies-master\Dependencies\Shell32IconExtractor.cs:line 63
   at Dependencies.ShellIcon.GetSmallIcon(String fileName) in C:\Users\RemkoW\source\repos\Dependencies-master\Dependencies\Shell32IconExtractor.cs:line 50
   at Dependencies.ImageToHeaderConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) in C:\Users\RemkoW\source\repos\Dependencies-master\Dependencies\Shell32IconExtractor.cs:line 74
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 954
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 902
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs:line 891
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Dependencies.App.Main()

        private static Icon GetIcon(string fileName, uint flags)
        {
            SHFILEINFO shinfo = new SHFILEINFO();
            IntPtr hImgSmall = Win32.SHGetFileInfo(fileName, 0, ref shinfo, (uint)Marshal.SizeOf(shinfo), Win32.SHGFI_ICON | flags);

            Icon icon = (Icon)System.Drawing.Icon.FromHandle(shinfo.hIcon).Clone();
            Win32.DestroyIcon(shinfo.hIcon);
            return icon;
        }

Problem is that both return value for SHGetFileInfo is not checked so if it fails hImgSmall and/or shinfo.hIcon can be null thus failing the call to System.Drawing.Icon.FromHandle.

**Comment by lucasg** [comment]
Good catch ! I've added the necessary check : 0f035b9b80cd9f152f06b70d2120ce5282a093aa
(You can grab an up-to-date version here : https://ci.appveyor.com/api/buildjobs/s5v9t84bpawa5bim/artifacts/output%2FDependencies.zip)
