### ISSUE TITLE
How to list missing dependencies via CLI?

### ISSUE THREAD

**Issue by tankorsmash** [lucasg/Dependencies#97]
dependencies.exe my_exe.exe

prints nothing at all (but I think that might be intentional). I can run `dependencies.exe my_exe.exe -knowndll` to see all the known DLLs and `dependencies.exe my_exe.exe -imports` to see all listed imports, and manually crossreference them, but there has to be a way to just get the missing ones.

Running `dependencies.exe my_exe.exe -modules` and `dependencies.exe my_exe.exe -chain` throw 

```c#
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 294
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.Program.DumpModules(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 503
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 591
```

But this isn't about that, so please let me know what the way to list the missing DLLs, if possible.

**Comment by tksharpless** [comment]
I'd find this very useful too, as would a great many others, I suspect.  If you implement it, please make the list of missing dlls visible in the GUI as well.

**Comment by lucasg** [comment]
@tankorsmash : this look like a bug, if you can find a way to give me the binaries involved, I might be able to fix the issue. Otherwise you can see it on the output log :

```
PS> .\Dependencies.exe -modules C:\python27-x64\python.exe --depth=1
[ROOT] python.exe : C:\python27-x64\python.exe
[WellKnownDlls] KERNEL32.dll : C:\Windows\system32\kernel32.dll
[WindowsFolder] python27.dll : C:\Windows\system32\python27.dll
[NOT_FOUND] MSVCR90.dll :
```
(grep for  `NOT_FOUND` markers)

@tksharpless : you can view "not found" modules in the GUI :
![image](https://user-images.githubusercontent.com/2520861/70393624-3297b200-19ec-11ea-8ef8-fa509c133fb0.png)

Right-click on the modules list view and select "view Module Search Order" and get the whole list of modules and how they were found or not :
![image](https://user-images.githubusercontent.com/2520861/70393633-5f4bc980-19ec-11ea-921d-da18fcac61c5.png)

**Comment by tankorsmash** [comment]
I'm using v1.9.0 of Dependencies and just to be sure, I also used a Python exe (download my version https://www.mediafire.com/file/jnks6yq6kkbao8d/python.exe/file) with a similar error:

```
PS C:\Users\asd\Downloads\Dependencies_x64_Release> .\Dependencies.exe -modules C:\Python27\python.exe -depth=1        
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 294
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 309
   at Dependencies.Program.DumpModules(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 503
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 591
```

**Comment by lucasg** [comment]
Can you test it with a up-to-date version please ? I think I fix the issue since v1.9 

link : https://ci.appveyor.com/project/lucasg/dependencies/builds/29397059/job/jgtmvrfsdn62kfni/artifacts

1.9 :
```
O:\Dependencies\Releases\Dependencies-v1.9\Dependencies.exe -modules C:\Users\user\Downloads\python.exe --depth=2

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 296
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencyItem.ResolveDependencies() in C:\projects\dependencies\Dependencies\Program.cs:line 311
   at Dependencies.PeDependencies..ctor(PE Application) in C:\projects\dependencies\Dependencies\Program.cs:line 373
   at Dependencies.Program.DumpModules(PE Pe, Action`1 Printer) in C:\projects\dependencies\Dependencies\Program.cs:line 503
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 591
```

master build :
```
O:\Dependencies\Dependencies\bin\Releasex64\Dependencies.exe -modules C:\Users\user\Downloads\python.exe --depth=2
[ROOT] python.exe : C:\Users\lucas\Downloads\python.exe
[ApiSetSchema] api-ms-win-core-rtlsupport-l1-1-0.dll : C:\Windows\SysWOW64\ntdll.dll
[ApiSetSchema] api-ms-win-core-rtlsupport-l1-2-0.dll : C:\Windows\SysWOW64\ntdll.dll
[ApiSetSchema] api-ms-win-core-processthreads-l1-1-0.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-processthreads-l1-1-3.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-processthreads-l1-1-2.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-processthreads-l1-1-1.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-registry-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-heap-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-heap-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-memory-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-memory-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-memory-l1-1-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-handle-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-synch-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-synch-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-synch-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l1-2-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-delayload-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-io-l1-1-0.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-io-l1-1-1.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-job-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-threadpool-legacy-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-threadpool-private-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-libraryloader-l1-2-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-libraryloader-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-libraryloader-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-libraryloader-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-namedpipe-l1-2-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-namedpipe-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-namedpipe-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-datetime-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-datetime-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-datetime-l1-1-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-sysinfo-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-sysinfo-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-sysinfo-l1-2-3.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-sysinfo-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-timezone-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-localization-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-localization-private-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-processenvironment-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-processenvironment-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-string-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-debug-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-debug-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-errorhandling-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-errorhandling-l1-1-3.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-fibers-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-util-l1-1-0.dll : C:\Windows\SysWOW64\kernel32.dll
[ApiSetSchema] api-ms-win-core-profile-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-security-base-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-security-base-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-realtime-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-systemtopology-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-systemtopology-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-processtopology-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-namespace-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l2-1-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l2-1-3.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-file-l2-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-localization-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-normalization-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-fibers-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-fibers-l2-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-sidebyside-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-appcompat-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-appcompat-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-windowserrorreporting-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-windowserrorreporting-l1-1-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-windowserrorreporting-l1-1-2.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l1-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l1-2-1.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l2-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l2-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-core-console-l3-2-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-security-appcontainer-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[ApiSetSchema] api-ms-win-eventing-provider-l1-1-0.dll : C:\Windows\SysWOW64\kernelbase.dll
[WellKnownDlls] KERNEL32.dll : C:\Windows\SysWOW64\kernel32.dll
[WellKnownDlls] ntdll.dll : C:\Windows\SysWOW64\ntdll.dll
[WellKnownDlls] KERNELBASE.dll : C:\Windows\SysWOW64\kernelbase.dll
[NOT_FOUND] python27.dll :
[NOT_FOUND] MSVCR90.dll :
[NOT_FOUND] api-ms-win-core-comm-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-wow64-l1-1-1.dll :
[NOT_FOUND] api-ms-win-core-wow64-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-xstate-l2-1-0.dll :
[NOT_FOUND] api-ms-win-core-xstate-l2-1-1.dll :
[NOT_FOUND] api-ms-win-core-psapi-l1-1-0.dll :
[NOT_FOUND] api-ms-win-core-psapi-ansi-l1-1-0.dll :
```

**Comment by tankorsmash** [comment]
Seems like it works for the Python exe for depth=1 (attached) and depth=2, and for my previous exe. Thank you!

```
PS C:\Users\asd\Downloads\Dependencies_x64_Release (1)> .\Dependencies.exe -modules C:\Python27\python.exe -depth=1    [ROOT] python.exe : C:\Python27\python.exe
[SxS] MSVCR90.dll : C:\WINDOWS\WinSxs\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
[WellKnownDlls] KERNEL32.dll : C:\WINDOWS\SysWOW64\kernel32.dll
[ApplicationDirectory] python27.dll : C:\Python27\python27.dll
PS C:\Users\asd\Downloads\Dependencies_x64_Release (1)>
```

**Comment by gmkado** [comment]
> @tankorsmash : this look like a bug, if you can find a way to give me the binaries involved, I might be able to fix the issue. Otherwise you can see it on the output log :
> 
> ```
> PS> .\Dependencies.exe -modules C:\python27-x64\python.exe --depth=1
> [ROOT] python.exe : C:\python27-x64\python.exe
> [WellKnownDlls] KERNEL32.dll : C:\Windows\system32\kernel32.dll
> [WindowsFolder] python27.dll : C:\Windows\system32\python27.dll
> [NOT_FOUND] MSVCR90.dll :
> ```
> 
> (grep for `NOT_FOUND` markers)
> 
> @tksharpless : you can view "not found" modules in the GUI : ![image](https://user-images.githubusercontent.com/2520861/70393624-3297b200-19ec-11ea-8ef8-fa509c133fb0.png)
> 
> Right-click on the modules list view and select "view Module Search Order" and get the whole list of modules and how they were found or not : ![image](https://user-images.githubusercontent.com/2520861/70393633-5f4bc980-19ec-11ea-921d-da18fcac61c5.png)

@lucasg not related to this issue, but this is exactly what I was looking for and not immediately obvious, what do you think about putting this tidbit in the README?
